### PR TITLE
Add Tynan Coffee & Tea

### PR DESCRIPTION
**Pull request by jgarber623**
Here you go, boss! ☕️

### CODE REVIEW

**Comment by jgarber623** [comment]
Spelling mistakes in commit messages… 😐

**Comment by paultag** [comment]
🇺🇸🇺🇸🇺🇸🇺🇸

**Comment by paultag** [comment]
Thanks, @jgarber623!

**Comment by jgarber623** [comment]
@paultag ☕️ ☕️ ☕️ 

https://www.youtube.com/watch?v=isEYI-4cdZo

**Pull request merged**
